version: 2
jobs:
  test-and-build:
    environment:
      - _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-buster-node
    steps:
      - checkout
      - run:
          name: cd datapotato
          command: cd datapotato
      - run:
          name: test datapotato clj
          command: clojure -X:test
      - run:
          name: test datapotato cljs
          command: clojure -X:test-cljs
      - run:
          name: Install bb
          command: |
            sudo bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)
      - run:
          name: Run bb tests
          command: bb test
      - run:
          name: Build datapotato
          command: clojure -T:build jar
      - run:
          name: cd datapotato-insert-next-jdbc
          command: cd datapotato-insert-next-jdbc
      - run:
          name: test datapotato-insert-next-jdbc clj
          command: clojure -X:test
      - run:
          name: Build datapotato-insert-next-jdbc
          command: clojure -T:build jar
      - save-cache:
          paths:
            - ~/bin
            - ~/.m2
          key: datapotato-{{ checksum "build.clj" }}
      - persist_to_workspace:
          root: ./
          paths:
            - ./
  deploy:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-buster-node
    steps:
      - checkout
      - restore_cache:
          key: datapotato-{{ checksum "build.clj" }}
      - attach_workspace:
          at: ./
      - run:
          name: Deploy datapotato to clojars
          command: cd datapotato && clojure -T:build deploy
      - run:
          name: Deploy datapotato-insert-next-jdbc to clojars
          command: cd ../datapotato-insert-next-jdbc && clojure -T:build deploy

workflows:
  version: 2
  deploy:
    jobs:
      - test-and-build
      - deploy:
          filters:
            branches:
              only:
                - main
                - v3.0.0
          requires:
            - test-and-build
